services:
  db:
    build:
      context: .
      dockerfile: images/postgres/Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - /var/lib/postgresql/data
      - ./data:/data
      - ./fabien_fdw:/fabien_fdw
    command:
      - "postgres"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_statement=all"